# Generated by Django 4.1.1 on 2022-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('opened_time', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('call_number', models.CharField(max_length=255)),
                ('map_image', models.ImageField(null=True, upload_to='appname')),
                ('thumbnail_image', models.ImageField(null=True, upload_to='appname')),
                ('image1', models.ImageField(null=True, upload_to='appname')),
                ('image2', models.ImageField(null=True, upload_to='appname')),
            ],
        ),
    ]
